# Generated by Django 5.1.3 on 2024-11-20 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('graduation_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('diplom', 'Diplom'), ('atestat', 'Atestat'), ('pasport', 'Pasport kopiya'), ('ariza', 'Ariza'), ('buyruq', 'Buyruqdan ko‘chirma'), ('reyting', 'Reyting'), ('bmi', 'BMI')], max_length=20)),
                ('is_available', models.BooleanField(default=False)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('shelf', models.CharField(blank=True, max_length=50, null=True)),
                ('row', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='arxiv.student')),
            ],
        ),
    ]
