# Generated by Django 5.1.3 on 2025-02-25 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abuturiyent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('surname', models.CharField(max_length=100, null=True, verbose_name='Sharif')),
                ('birthday', models.DateField(null=True, verbose_name="Tug'ilgan kun")),
                ('abuturiyent_id', models.CharField(max_length=20, verbose_name='Abituriyent ID')),
                ('graduation_year', models.CharField(max_length=1000, null=True, verbose_name='Hujjat topshirgan yili')),
            ],
            options={
                'verbose_name': 'Abituriyent',
                'verbose_name_plural': 'Abituriyentlar',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('surname', models.CharField(max_length=100, null=True, verbose_name='Sharif')),
                ('employee_id', models.CharField(max_length=20, verbose_name='Xodim ID')),
                ('birthday', models.DateField(null=True, verbose_name="Tug'ilgan kun")),
                ('arrived_year', models.CharField(max_length=1000, null=True, verbose_name='Kelgan yili')),
                ('gone_year', models.CharField(max_length=1000, null=True, verbose_name='Ketgan yili')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50, verbose_name='Hona')),
                ('shelf', models.CharField(max_length=50, verbose_name='Shkaf')),
            ],
            options={
                'verbose_name': 'Joylashuv',
                'verbose_name_plural': 'Joylashuvlar',
            },
        ),
        migrations.CreateModel(
            name='DocumentAbuturiyent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('diplom', 'Diplom'), ('atestatsiya', 'Atestatsiya')], max_length=20, verbose_name='Hujjat turi')),
                ('is_available', models.BooleanField(default=False, verbose_name='Tasdiqlash')),
                ('abuturiyent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='arxiv.abuturiyent', verbose_name='Abituriyent')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='DocumentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('turdavoy', 'Mexnat daftarcha'), ('t-2', 'T-2')], max_length=20, verbose_name='Hujjat turi')),
                ('is_available', models.BooleanField(default=False, verbose_name='Tasdiqlash')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='arxiv.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arxiv.location', verbose_name='Joylashuv'),
        ),
        migrations.AddField(
            model_name='abuturiyent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arxiv.location', verbose_name='Joylashuv'),
        ),
        migrations.CreateModel(
            name='Magister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('surname', models.CharField(max_length=100, null=True, verbose_name='Sharif')),
                ('birthday', models.DateField(null=True, verbose_name="Tug'ilgan kun")),
                ('srtqi_id', models.CharField(max_length=20, verbose_name='Magistr ID')),
                ('graduation_year', models.CharField(max_length=1000, null=True, verbose_name='Tugatgan yil')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arxiv.location', verbose_name='Joylashuv')),
            ],
            options={
                'verbose_name': 'Magistr',
                'verbose_name_plural': 'Magistrantlar',
            },
        ),
        migrations.CreateModel(
            name='DocumentMagister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('diplom1', 'Diplom Universitet'), ('diplom2', 'Diplom Kollej'), ('atestat', 'Atestat'), ('buyruq1', "Buyruqdan ko'chirma 1-kurs"), ('buyruq2', "Buyruqdan ko'chirma 2-kurs"), ('buyruq5', 'Bitirgan'), ('achsleniya', 'Achisleniya'), ('reyting', 'Reyting'), ('md', 'MD')], max_length=20, verbose_name='Hujjat turi')),
                ('is_available', models.BooleanField(default=False, verbose_name='Tasdiqlash')),
                ('magister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='arxiv.magister', verbose_name='Magistr')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='SrtqiStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('surname', models.CharField(max_length=100, null=True, verbose_name='Sharif')),
                ('birthday', models.DateField(null=True, verbose_name="Tug'ilgan kun")),
                ('srtqi_id', models.CharField(max_length=20, verbose_name='Sirqi talaba ID')),
                ('graduation_year', models.CharField(max_length=1000, null=True, verbose_name='Bitirgan yil')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arxiv.location', verbose_name='Joylashuv')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSrtqiStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('diplom1', 'Diplom Universitet'), ('diplom2', 'Diplom Kollej'), ('atestat', 'Atestat'), ('buyruq1', "Buyruqdan ko'chirma 1-kurs"), ('buyruq2', "Buyruqdan ko'chirma 2-kurs"), ('buyruq3', "Buyruqdan ko'chirma 3-kurs"), ('buyruq4', "Buyruqdan ko'chirma 4-kurs"), ('buyruq5', "Buyruqdan ko'chirma 5-kurs"), ('bitirgan', 'Bitirgan'), ('achsleniya', 'Achisleniya'), ('reyting', 'Reyting'), ('bmi', 'BMI')], max_length=20, verbose_name='Hujjat turi')),
                ('is_available', models.BooleanField(default=False, verbose_name='Tasdiqlash')),
                ('srtqistudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='arxiv.srtqistudent', verbose_name='Sirqi talaba')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('surname', models.CharField(max_length=100, null=True, verbose_name='Sharif')),
                ('student_id', models.CharField(max_length=20, verbose_name='Talaba ID')),
                ('birthday', models.DateField(null=True, verbose_name="Tug'ilgan kun")),
                ('graduation_year', models.CharField(max_length=1000, null=True, verbose_name='Bitirgan yil')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arxiv.location', verbose_name='Joylashuv')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('diplom1', 'Diplom Universitet'), ('diplom2', 'Diplom Kollej'), ('atestat', 'Atestat'), ('buyruq1', "Buyruqdan ko'chirma 1-kurs"), ('buyruq2', "Buyruqdan ko'chirma 2-kurs"), ('buyruq3', "Buyruqdan ko'chirma 3-kurs"), ('buyruq4', "Buyruqdan ko'chirma 4-kurs"), ('buyruq5', 'Bitirgan'), ('achsleniya', 'Achisleniya'), ('reyting', 'Reyting'), ('bmi', 'BMI')], max_length=20, verbose_name='Hujjat turi')),
                ('is_available', models.BooleanField(default=False, verbose_name='Tasdiqlash')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='arxiv.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
    ]
