# Generated by Django 5.1.3 on 2024-11-20 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('shelf', models.CharField(max_length=50)),
                ('row', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='room',
        ),
        migrations.RemoveField(
            model_name='document',
            name='row',
        ),
        migrations.RemoveField(
            model_name='document',
            name='shelf',
        ),
        migrations.AddField(
            model_name='document',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arxiv.location'),
        ),
    ]
