# Generated by Django 5.1.3 on 2024-11-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0002_location_remove_document_room_remove_document_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('diplom1', 'Diplom Universitet'), ('diplom2', 'Diplom Kollej'), ('atestat', 'Atestat'), ('buyruq1', "Buyruqdan ko'chirma 1-kurs"), ('buyruq2', "Buyruqdan ko'chirma 2-kurs"), ('buyruq3', "Buyruqdan ko'chirma 3-kurs"), ('buyruq4', "Buyruqdan ko'chirma 4-kurs"), ('buyruq5', "Buyruqdan ko'chirma 5-kurs"), ('reyting', 'Reyting'), ('bmi', 'BMI'), ('md', 'MD')], max_length=20),
        ),
    ]
