# Generated by Django 5.1.3 on 2024-11-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0003_alter_document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
