# Generated by Django 5.1.3 on 2024-11-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0004_student_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
