# Generated by Django 5.1.3 on 2024-11-25 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0005_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='location',
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arxiv.location'),
        ),
    ]
