# Generated by Django 4.2.16 on 2024-11-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0007_abuturiyent_employee_documentemployee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abuturiyent',
            old_name='employe_id',
            new_name='abuturiyent_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employe_id',
            new_name='employee_id',
        ),
    ]
