# Generated by Django 5.1.3 on 2024-11-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0008_rename_employe_id_abuturiyent_abuturiyent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('diplom1', 'Diplom Universitet'), ('diplom2', 'Diplom Kollej'), ('atestat', 'Atestat'), ('buyruq1', "Buyruqdan ko'chirma 1-kurs"), ('buyruq2', "Buyruqdan ko'chirma 2-kurs"), ('buyruq3', "Buyruqdan ko'chirma 3-kurs"), ('buyruq4', "Buyruqdan ko'chirma 4-kurs"), ('buyruq5', "Buyruqdan ko'chirma 5-kurs"), ('achsleniya', 'Achisleniya'), ('reyting', 'Reyting'), ('bmi', 'BMI'), ('md', 'MD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentemployee',
            name='doc_type',
            field=models.CharField(choices=[('turdavoy', 'Turdavoy'), ('t-2', 'T-2'), ('kadrlar', 'Kadrlar')], max_length=20),
        ),
    ]
