# Generated by Django 5.1.3 on 2024-12-17 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0009_alter_document_doc_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='location',
            name='row',
        ),
        migrations.AddField(
            model_name='abuturiyent',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='arrived_year',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gone_year',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='abuturiyent',
            name='graduation_year',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('diplom1', 'Diplom Universitet'), ('diplom2', 'Diplom Kollej'), ('atestat', 'Atestat'), ('buyruq1', "Buyruqdan ko'chirma 1-kurs"), ('buyruq2', "Buyruqdan ko'chirma 2-kurs"), ('buyruq3', "Buyruqdan ko'chirma 3-kurs"), ('buyruq4', "Buyruqdan ko'chirma 4-kurs"), ('buyruq5', 'Bitirgan'), ('achsleniya', 'Achisleniya'), ('reyting', 'Reyting'), ('bmi', 'BMI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentemployee',
            name='doc_type',
            field=models.CharField(choices=[('turdavoy', 'Mexnat daftarcha'), ('t-2', 'T-2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_year',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Magister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('birthday', models.DateField(null=True)),
                ('srtqi_id', models.CharField(max_length=20)),
                ('graduation_year', models.CharField(max_length=1000, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arxiv.location')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMagister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('diplom1', 'Diplom Universitet'), ('diplom2', 'Diplom Kollej'), ('atestat', 'Atestat'), ('buyruq1', "Buyruqdan ko'chirma 1-kurs"), ('buyruq2', "Buyruqdan ko'chirma 2-kurs"), ('buyruq5', 'Bitirgan'), ('achsleniya', 'Achisleniya'), ('reyting', 'Reyting'), ('md', 'MD')], max_length=20)),
                ('is_available', models.BooleanField(default=False)),
                ('magister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='arxiv.magister')),
            ],
        ),
        migrations.CreateModel(
            name='SrtqiStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('birthday', models.DateField(null=True)),
                ('srtqi_id', models.CharField(max_length=20)),
                ('graduation_year', models.CharField(max_length=1000, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arxiv.location')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSrtqiStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('diplom1', 'Diplom Universitet'), ('diplom2', 'Diplom Kollej'), ('atestat', 'Atestat'), ('buyruq1', "Buyruqdan ko'chirma 1-kurs"), ('buyruq2', "Buyruqdan ko'chirma 2-kurs"), ('buyruq3', "Buyruqdan ko'chirma 3-kurs"), ('buyruq4', "Buyruqdan ko'chirma 4-kurs"), ('buyruq5', "Buyruqdan ko'chirma 5-kurs"), ('bitirgan', 'Bitirgan'), ('achsleniya', 'Achisleniya'), ('reyting', 'Reyting'), ('bmi', 'BMI')], max_length=20)),
                ('is_available', models.BooleanField(default=False)),
                ('srtqistudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='arxiv.srtqistudent')),
            ],
        ),
    ]
